name: release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Build package
        run: npm run build

      - name: Version and Publish
        uses: changesets/action@v1
        with:
          version: npm run cversion
          publish: npm run release
          title: 'chore: new release candidate'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Version is $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Stage changes
        run: git add package.json package-lock.json

      - name: Commit with version in message
        run: |
          git commit -m "chore: new release ${{ steps.extract_version.outputs.version }}"
          git push
