name: Revert Package Files Changes

on:
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  revert-package-files:
    if: startsWith(github.head_ref, 'liblab')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Fetch main branch and revert package files changes
        run: |
          git fetch origin main
          git checkout origin/main -- package.json package-lock.json
          git commit -m "Revert changes to package files" package.json package-lock.json
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
